services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: url_shortener:latest
    container_name: url_shortener_app
    depends_on:
      - redis
    volumes:
      - ./config:/root/config
      - ./static:/root/static
    ports:
      - "38080:8081"
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "redis-url-shortener-qwenjklqjw6987#sa"]
    environment:
      - REDIS_PASSWORD=redis-url-shortener-qwenjklqjw6987#sa
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: